default:
  type: segment
  url: /^\/([a-z]+)\/([a-z]+)\/([a-z]+)$/
  module: $1
  controller: $2
  action: $3

default_id:
  type: segment
  url: /^\/([a-z]+)\/([a-z]+)\/([a-z]+)\/([0-9]+)$/
  module: $1
  controller: $2
  action: $3
  params: 
    id: $4

index:
  type: named
  url: /^\/$/
  module: store
  controller: index
  action: index